spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url : ${URL}
    username: ${USER}
    password: ${PASSWORD}

  logging:
    level:
      org:
        hibernate:
          SQL: debug

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update

jwt:
  secret-key: ${SECRET-KEY}
  access-token-exp: ${ACCESS-EXP}
  refresh-token-exp: ${REFRESH-EXP}